import type { Metadata } from 'next'
import { Alata } from 'next/font/google'
import './globals.css'
import {TheHeader} from "@/components/Header/TheHeader";

const alata = Alata({weight: '400', style: 'normal'})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <TheHeader/>
      <body className={alata.className}>{children}</body>
    </html>
  )
}
