import type { Metadata } from 'next'
import { Alata } from 'next/font/google'
import './globals.css'
import {TheHeader} from "@/components/Header/TheHeader";
import {StoreProvider} from "@/store/Provider/StoreProvider";

const alata = Alata({weight: '400', subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {

  return (
      <StoreProvider>
        <html lang="en">
        <TheHeader/>
        <body className={alata.className}>{children}</body>
        </html>
      </StoreProvider>
  )
}
